version: "3.9"
services:
  keycloak:
    build:
      context: ./keycloak
    ports:
      - "8443:8443"
    depends_on:
      - keycloakdb
    volumes:
      - /etc/letsencrypt/live/tradexclub.ru/fullchain.pem:/opt/keycloak/conf/fullchain.pem
      - /etc/letsencrypt/live/tradexclub.ru/privkey.pem:/opt/keycloak/conf/privkey.pem


  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  process.service:
    build:
      context: ./process.service
    ports: 
      - "7165:443"
    volumes:
      - /etc/letsencrypt/live/tradexclub.ru/fullchain.pem:/app/https.crt
      - /etc/letsencrypt/live/tradexclub.ru/privkey.pem:/app/https.key
    depends_on:
      - keycloakdb

  process.client:
    build:
      context: ./process.client
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/tradexclub.ru/fullchain.pem:/etc/nginx/certs/server.crt
      - /etc/letsencrypt/live/tradexclub.ru/privkey.pem:/etc/nginx/certs/server.key
    depends_on:
      - process.service

volumes:
  postgres_data:
  process_data:
