version: "3.9"
services:
  keycloak:
    build:
      context: ./keycloak
    ports:
      - "8443:8443"
    depends_on:
      - keycloakdb

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  process.service:
    build:
      context: ./process.service
    ports: 
      - "7165:443"
    depends_on:
      - keycloakdb

  process.client:
    build:
      context: ./process.client
    ports:
      - "443:443"
    depends_on:
      - process.service

volumes:
  postgres_data:
  process_data:
